title: Apex Orbit Framework (AOF)
description: A lightweight, scalable, and easy-to-use Salesforce Apex framework
show_downloads: true
google_analytics:
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one